version: '3'
services:
  apache-php:
    build: .docker/apache-php
    container_name: sockets_apache_php
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .docker/apache-php/datetime.ini:/usr/local/etc/php/conf.d/datetime.ini
      - .docker/apache-php/vhost.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/html
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=docker_concurrency"
      XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost remote_enable=on"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    build: .docker/db
    restart: always
    command: mysqld --sql_mode="STRICT_TRANS_TABLES"
    environment:
      - MYSQL_DATABASE=concurrency
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - .docker/db/data/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306